server:
  port: 8000
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: fuad
  datasource:
    url: jdbc:postgresql://localhost:5432/relation
    username: postgres
    password: esscsmfu2
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
#  security:
#    user:
#      name: fuad
#      password: 123123